version: '3'
services:
  payment_router:
    image: node:10-alpine
    working_dir: /usr/local/app
    command: npm run start:dev
    restart: on-failure
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/local/app
    networks:
      - payment_router

  mongo_payment_router:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDBPaymentRouter!
    ports:
      - '27017:27017'
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    networks:
      - payment_router

networks:
  payment_router:
    external:
      name: payment_router
